### PR TITLE
Pie test

### PR DESCRIPTION
**Pull request by Pikacrazy**
made the data from the pie chart accurate, fixed printing bug
- color changing feature!
-New legends (accurate to arrays)
-percentage conversion feature in progress

### CODE REVIEW

**Comment by ZichengLiang** [comment]
Great progress Muireann! That's a lot of things you've done!!

Sorry I was busy with my family stuff today, I will test the changes tomorrow and get back to you!

**Comment by ZichengLiang** [comment]
@Brigandus 

Oliver, sorry to interrupt you during the weekend. 

Could you check them as well when you're good? As these codes might have connections with yours.

**Review by Brigandus — CHANGES_REQUESTED** [review]
The only problem that I have with this is in the PieChart class. In the draw function, you will see the background instruction. This should be removed. 
Apart from that it all looks good

**Comment by ZichengLiang** [comment]
@Pikacrazy 

Hi Muireann, please see above the review given by Oliver and make some improvements accordingly!

After this we can merge this pull request into our main branch!

Really a good job!

**Pull request merged**
